name: 'Run ktlint with reviewdog'
description: '🐶 Run ktlint with reviewdog on pull requests to enforce best practices'
author: 'Qminder'

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
branding:
  icon: 'edit'
  color: 'blue'
